# Generated by Django 5.2.11 on 2026-02-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regid', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
